### ISSUE TITLE
Graph nodes not laid out properly

### ISSUE THREAD

**Issue by umdstu** [cytoscape/cytoscape.js-cose-bilkent#100]
Using the `cose` layout produced a graph that looked as I expected, but it was simply a bit slow for my 1773 nodes and 1593 edges for some reason. So I tried fcose and most recently cose-bilkent as alternatives. Unfortunately the graph is just a single massive clump of nodes essentially layered on top of one another when I use thesee. But cose-bilkent is much faster (doesn't lock up my browser either like cose!).

I used all default options so I do not believe i'm 'using it wrong', and it looks fine for normal cose layout, so thinking something might be wrong with the library rather than my data.

Save for the data, what can I provide to help you resolve this possible bug?

Thanks!

**Comment by ugurdogrusoz** [comment]
@umdstu I am not sure what you're reporting. A potential bug without providing us your graph or even a picture of what it looked like after layout?
If what you have is a single massive clump of nodes, no layout is going to produce anything useful even if they return fast. I suggest some what to manage your graph's complexity either by clustering, filtering, etc. and using an extension such as [this](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse).
Provide us your graph if you would like us to investigate a potential bug.

**Comment by umdstu** [comment]
My apologies for the lack of information and clarity. I do not currently have access to the data or the graph from here, which is why I did not include it.

The data has insightful clusters in them, as seen when usying the built-in 'cose' layout. There are 4 discrete large clusters, and then lots of independenent and 3 node clusters below that. 

However when I switch to cose-bilkent, it only appears as though it's a single massive clump, because everything is stacked on top of one another in a large circle. I expected this to look similar to the 'cose' layout, but with the performance improvements.

I will attach an ms paint photo to show what I'm talking about. The first is with 'cose' and the second with 'cose-bilken'.

Hope it clarifies. And I understand if you still aren't able to help me.

![cose](https://user-images.githubusercontent.com/1298036/86264705-dd420e80-bb90-11ea-93c2-f64183833539.png)
![cose-bilken](https://user-images.githubusercontent.com/1298036/86264741-e4691c80-bb90-11ea-91a1-585bf4a3cbf9.png)

**Comment by ugurdogrusoz** [comment]
I really don't understand. What's a cluster? Are they actual nodes? Or graph components? In cose version your clusters are connected, in cose-bilkent version, they aren't! 
Please provide a JSFiddle or JSBin demo to reproduce this issue or else we won't be able to help.

**Comment by umdstu** [comment]
A cluster is a group of connected nodes. No components are on the graph.

I didn't realize that the cose-bilkent produced entirely different views than the cose algorithm. I thought it was just a faster version of the cose algorithm, my apologies for the misunderstanding. I'm sure my results are normal in this case. Thanks.
