### ISSUE TITLE
Layout always builds strictly to canvas bounds

### ISSUE THREAD

**Issue by heyjohnnyfunt** [cytoscape/cytoscape.js-cose-bilkent#15]
Hi, I don't know exactly is it an issue, or just a normal behavior. But cose-bilkent always makes my nodes fit the canvas bounds. So if i have the square one, nodes that place closer to the canvas bounds will always go one after another like if I use boundingBox param of original CoSe mode. 
How can I fix that issue?

**Comment by ugurdogrusoz** [comment]
Could you please provide an example? A screenshot perhaps?

**Comment by heyjohnnyfunt** [comment]
Yeap, here are the screens (sorry, i can only provide it in awful quality). The first one refers to the issue, the second is something I wan't to see. But there is one hardship. I get the second layout only if the spacing between nodes is not as large as I want (nodeRepulsion param).
For **the first layout** I've got such options configured:
`var options = {
            name: 'cose-bilkent',
            ready: function () {
                cy.resize();
            },
            stop: function () {
            },
            fit: true,             
            padding: 30,            
            randomize: true,     
            nodeRepulsion: 200000,   
            idealEdgeLength: 400,    
            edgeElasticity: 0.9,       
            nestingFactor: 0.9,        
            gravity: 0.1,             
            numIter: 2500,        
            tile: true,                
            animate: true,             
            tilingPaddingVertical: 80,  
            tilingPaddingHorizontal: 80
        };`

And **for the second** (good looking) one I've got:
` var options = {
            name: 'cose-bilkent',
            ready: function () {
                cy.resize();
            },
            stop: function () {
            },
            fit: true,                 
            padding: 30,               
            randomize: true,            
            nodeRepulsion: 65000, 
            idealEdgeLength: 300, 
            edgeElasticity: 0.8,
            nestingFactor: 0.1, 
            gravity: 0.4, 
            numIter: 2500,
            tile: true,
            animate: true
        };`

Maybe I'm missing something, but I want the two conditions are met:
1. I want **large spacing between nodes** to force them not to overlap.
2. I want to see the layout **not in square box**.

![1](https://cloud.githubusercontent.com/assets/12138428/15574274/12572a0c-2355-11e6-8eef-7e31a08a43fe.png)
![2](https://cloud.githubusercontent.com/assets/12138428/15574328/5fa05db0-2355-11e6-89dd-e5b43c2f24cc.png)

**Comment by ugurdogrusoz** [comment]
This is due to the gravity range and factor. Gravity forces in CoSE are applied to keep disconnected parts of a graph together. For efficiency reasons, they are applied only when nodes are within a certain range of the graph center. We increased this range along with decreasing the gravity constant. You shouldn't have this problem in the latest release since we changed some defaults to avoid this: https://github.com/cytoscape/cytoscape.js-cose-bilkent/commit/9642c3325180d326d50e98dad8ee71f867fb0395.
If you don't want to upgrade to the latest release of cose-bilkent, I suggest you make the similar changes in your own repo/copy.

**Comment by heyjohnnyfunt** [comment]
Thanks for the tips!
However, I'm already using 1.3.2 version. I've managed to make layout look better. But it's still not perfect. What is the highest value for gravity?
And what can I tune also?

**Comment by ugurdogrusoz** [comment]
The smaller the gravity factor the less square looking your drawings should be. Please let us know if you're still unhappy with the shape of your drawings; perhaps we can expose the range factor or further adjust to avoid such situations.

**Comment by heyjohnnyfunt** [comment]
I've played around with gravity factor and noticed, that **if I set it to < 1**, then the square shape appears. And **if I set it up to something like 2, 3 or even higher**, then it look better (but not ideal).

Also there is one more little issue. Comparing with the default CoSe algorythm, Cose-Bilkent builds layout too long. I don't know how to make it faster. I've got sometimes one graph with almost 100 vertices, and somethimes multiple graphs with 10 to 20 vertices in each, and they (graphs) should be placed separetely.
Maybe I should use smaller cytoscape vertecies and their label sizes or something else? I'm realy confused, how to make it look better...

**Comment by ugurdogrusoz** [comment]
I suppose you mean DEFAULT_GRAVITY_RANGE_FACTOR. So you like layout results better when this is increased. We will go ahead and increase this factor to 3.8 by default. Can you please tell us what you mean by looks better but not ideal though? Frankly, even though the overall shape of layouts are "square" looking, by the general graph drawing criteria (no node overlaps, minimal edge-edge crossings, minimal area, uniform edge length, etc.) both layouts you provided are good. 

Regarding speed, cose-bilkent is a much more involved implementation than cose. I wouldn't expect cose to yield nearly as good layouts as cose-bilkent. There are many improvements planned (e.g. laying out components of a disconnected graph separately, and then packing them) for reducing speed but no parameter tuning is going to get you faster layouts at this point.

**Comment by heyjohnnyfunt** [comment]
I mean, that it looks like square, but with round corners. As you see on the picture below, the left and the right sides of the graph are aligned, therefor some edges does not look like "natural" as they bend too abruptly.

![image](https://cloud.githubusercontent.com/assets/12138428/15672328/bde65550-2738-11e6-833f-aee94386b0a2.png)

Yes, no doubt it's much better, than default cose. I've been using another visualization library (vis.js) and it's implementation is as good as yours, but works much faster.. i don't know why, may be some of my settings are incorrect.

If it's not too complicated, could you pls provide efficient options for cose-bilkent? 
Thanks for your support!

**Comment by ugurdogrusoz** [comment]
We already further increased DEFAULT_GRAVITY_RANGE_FACTOR (to 3.8) as I said.
Unfortunately the way to speed up the algorithm is not straightforward. We'll try to get it done by the end of summer but don't take it as a promise. The only way to speed it up as it is might be by decreasing numIter option (sacrificing quality for time).

**Comment by ugurdogrusoz** [comment]
See new issue #16
