### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js-cose-bilkent#16]
As mentioned in #15 as well, the peformance of the algorithm could be improved (mostly to speed it up) by a number of things:
- implement disconnected graph layout algorithms to separately lay out components of a disconnected graph and pack them at the end
- use FR grid variant to avoid calculating repulsion forces with all other nodes
- use multi-level scaling
- reduce trees
- profile to identify bottlenecks and try to improve those functions

**Comment by maxkfranz** [comment]
Each component could be run in a separate thread

**Comment by ugurdogrusoz** [comment]
Sure @maxkfranz

**Comment by stuartpb** [comment]
Any progress on the tree reduction? Would to be possible to merge that into the mainline `cose` implementation?

**Comment by ugurdogrusoz** [comment]
@stuartpb Sorry didn't have time and resources for this just yet. We hope to work on this over the Spring though.

**Comment by Prophet32j** [comment]
+1 on getting performance improvements with using threads

**Comment by Prophet32j** [comment]
This has been open for over a year. What's the progress on this?

**Comment by maxkfranz** [comment]
Not possible unless this layout uses a functional coding style. Even then not practical until browsers implement proper shared memory threads

**Comment by ugurdogrusoz** [comment]
There's been great performance improvements recently due to work by @hasanbalci and @kinimesi 
- FR grid variant implementation to reduce repulsion force calculation overhead
- Tree reduction to reduce size (and hence time)
- Several miscellaneous optimizations in choice of data structures
The result is a several fold speedup in running time on the average. This is to be released soon.
We will continue working on improving running time.

**Comment by ugurdogrusoz** [comment]
If not happy with run time performance of cose-bilkent, use fcose layout style.
