### ISSUE TITLE
Expose some more parameters as options

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js-cose-bilkent#17]
Can we please expose the following parameters as options:
- gravityRangeFactor -> gravityRange // Gravity range (constant)
- compoundGravityConstant -> gravityCompound // Gravity force (constant) for compounds
- compoundGravityRangeFactor -> gravityRangeCompound // Gravity range (constant) for compounds
- PER_LEVEL_IDEAL_EDGE_LENGTH_FACTOR used in calculating idealLength -> edgeLengthCompound // Additional edge length (constant) per nesting level

**Comment by metincansiper** [comment]
I exposed these parameters expect "edgeLengthCompound" because "PER_LEVEL_IDEAL_EDGE_LENGTH_FACTOR" is already controlled by another exposed parameter called "nestingFactor". After these changes I published version 1.3.6
