### ISSUE TITLE
How to avoid edge intersection

### ISSUE THREAD

**Issue by heyjohnnyfunt** [cytoscape/cytoscape.js-cose-bilkent#20]
Hi, I'm trying to make my graph look pretty with straightforward edges between vertexes that could make a path without edge intersections. As you see in the picture below, cose-bilkent always sets nodes illogically, so there edges are crossing. How can I avoid that? Thank you.
![default](https://cloud.githubusercontent.com/assets/12138428/16759589/6441cb02-4820-11e6-9000-bd52497e21d8.png)

**Comment by ugurdogrusoz** [comment]
Hi There! Spring embedders (force-directed layout algorithms) do not account for edge-to-edge crossings, and CoSE is a spring embedder. However, some additional heuristics do help with such crossings. Among them is reduction of trees (degree one nodes) planned for the (not so short term) future (see #16).

**Comment by chanana** [comment]
For people who happen to reach here by google sometime in the future, another way to reduce edge crossings is to use the yFiles layouts. Install the yFiles layouts through Cytoscape Apps. [Based on their website](https://www.yworks.com/products/yfiles-layout-algorithms-for-cytoscape), the yFiles Hierarchic and Organic layouts seek to minimize edge crossings.
