### ISSUE TITLE
temporary properties stored in data

### ISSUE THREAD

**Issue by bastiion** [cytoscape/cytoscape.js-cose-bilkent#23]
I use several layout algorithms in  a project, where the user can choose out of a list of layouts. For the case-bilkent layout I recognized an added property in the data section of nodes called `dummy_parent_id` and sometimes `tempchildren`.
This messes up the data-editor as my app assumes that only clean data is stored there. Cytoscape.JS has a `scratch`-store for such things, that to my opinion is much more suitable in this particular case.
I made some small modifications in order to store the data in `scratch` instead of `data`.

see PR #24

**Comment by hasanbalci** [comment]
I think this is solved.
