### ISSUE TITLE
Issue with nested compound nodes layout.

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js-cose-bilkent#25]
I have nested compound nodes but it seems that cose-bilkent failed to layout them properly. Basically in the end all nodes end-up on the same position.

see http://jsbin.com/qacuzalobi/edit?html,console,output

**Comment by metincansiper** [comment]
Interestingly in this graph all nodes end-up the same positions. I think that it must be a bug appearing rarely. In this demo ( http://htmlpreview.github.io/?https://github.com/cytoscape/cytoscape.js-cose-bilkent/blob/master/demo-compound.html )  cose-bilkent layout a nested graph successfully.

**Comment by aindlq** [comment]
Apparently it is not related to nested compounds. This more general issue, here is the same behaviour with only one compound node http://jsbin.com/dirurisiti/edit?html,output.

**Comment by aindlq** [comment]
ok, so this happens if node inside compound node has edge to parent node. I simplified previous example.

**Comment by ugurdogrusoz** [comment]
@aindlq CoSE layout cannot handle such "cyclic" edges and probably just returns without performing layout. If your application allows such edges, simply temporarily remove them before calling cose-bilkent layout.

**Comment by aindlq** [comment]
Thank you for your help! It works if I filter edges before layouting.
