### ISSUE TITLE
Layout doesn't consider node paddings.

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js-cose-bilkent#26]
Here is example without paddings - http://jsbin.com/qodotekale/1/edit?html,output , it works as expected.
And here is example with node paddings - http://jsbin.com/qowekuvofa/1/edit?html,output , as you can see nodes are overlaping.

Also for the reference, with simple cose layout nodes are not overlapping, see http://jsbin.com/tejufolire/1/edit?output

**Comment by ugurdogrusoz** [comment]
@aindlq see paddingCompound option. I think this is what you asked for.
