### ISSUE TITLE
Distance between nodes

### ISSUE THREAD

**Issue by superbobry** [cytoscape/cytoscape.js-cose-bilkent#27]
I have two types of nodes: atomic statements (rectangles) and logical operations (AND, OR, NOT), and I wan't to enforce the constraint that logical operations are well distanced from each other. 

![image](https://cloud.githubusercontent.com/assets/185856/17851669/dfc49758-686b-11e6-8c72-1488c4dbffb7.png)

Is there a way to do that using `cose-bilkent`?

**Comment by ugurdogrusoz** [comment]
The short answer is no. Spring embedders including cose-bilkent do apply repulsion forces on nodes to avoid overlaps and put some minimal distance between nodes. I can't see the whole picture in your example but the reason that some nodes (AND, OR, ProteinCoding, and HCP) are not nicely distanced from each other might be cause your graph is very dense and the algorithm cannot satisfy all the constraints.

**Comment by maxkfranz** [comment]
@superbobry If your data is a DAG/tree -- which logical AND / OR statements usually are -- you can also try the Dagre layout.  Dagre is designed just for DAGs.

When using CoSE, you may have to alter the options for the force values to get a nice result.  What values work well can be very different for different graphs, so you usually have to experiment a bit.

**Comment by superbobry** [comment]
@ugurdogrusoz, @maxkfranz thank you very much for the explanation. I will give Dagre a try.

**Comment by AllanDickerman** [comment]
Do you know of a layout where I specify measured distances between nodes (edge lengths)
and the layout tries to place nodes so as to minimize distortions to the specified edge lengths?
One application is where nodes are genes and distances are measured (DNA sequence or perhaps recombination probability).
I want a map that tries to reconcile the measured distances with minimal distortion.

**Comment by maxkfranz** [comment]
> Do you know of a layout where I specify measured distances between nodes (edge lengths)
> and the layout tries to place nodes so as to minimize distortions to the specified edge lengths?
> One application is where nodes are genes and distances are measured (DNA sequence or perhaps recombination probability).
> I want a map that tries to reconcile the measured distances with minimal distortion.

@AllanDickerman 

Layouts like FCOSE and Cola allow for this.  Simply set the values affecting edge length appropriately (e.g. `idealEdgeLength` and `edgeElasticity` in FCOSE).  The [Cola demo](https://js.cytoscape.org/demos/colajs-graph/) sets [edge length proportional to the inverse of weight](https://github.com/cytoscape/cytoscape.js/blob/9635c63cad2eeb91c873759226f70d9c428ace1d/documentation/demos/colajs-graph/code.js#L104) (i.e. closer nodes tend to be more related).  [GeneMANIA](https://genemania.org/search/homo-sapiens/tnf) does the same thing with COSE.

N.b. if you overconstrain the system (e.g. with a large, dense network), then the lengths won't correspond well to your metric.
