### ISSUE TITLE
`animate:'end'` doesn't work at init

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-cose-bilkent#29]
If you use this layout as the one specified at init, the animation doesn't work.  It just flashes quickly

**Comment by hasanbalci** [comment]
Can you give more detail about this bug? Which values do you use for options fit and randomize? 
We now disabled the post layout transform if the layout is incremental, so it may have solved the problem.

**Comment by maxkfranz** [comment]
It seems to be fixed in 2.0.2: https://jsbin.com/ququdal/1/edit?js,output

Maybe it was an issue with the timeout that was removed.

**Comment by ugurdogrusoz** [comment]
Great, closing then
