### ISSUE TITLE
RequireJs RegCos undefined

### ISSUE THREAD

**Issue by jdrudolph** [cytoscape/cytoscape.js-cose-bilkent#30]
My project uses `require.js` but registering the extension did not work since `regCose` remains undefined. Without registering the extension cytoscape was unable to find the layout `cose-bilkent`.

    require(['cytoscape', 'cytoscape-cose-bilkent'], function( cytoscape, regCose ){
      regCose( cytoscape ); // register extension
    });

Any ideas why this would happen? How I can test that I'm doing things correctly?

**Comment by maxkfranz** [comment]
Use 1.4.1

**Comment by jdrudolph** [comment]
I tried it again with the latest version but it's not working with the following error printed to the dev-tools console:

    Uncaught TypeError: cytoscape is not a function
        at register (src:9)

Clicking on `(src:9)` shows the following code snippet:

    'use strict';

    // registers the extension on a cytoscape lib ref
    var getLayout = require('./Layout');

    var register = function( cytoscape ){
      var Layout = getLayout( cytoscape );

      cytoscape('layout', 'cose-bilkent', Layout);    // <=== line producing the error
    };

    if( typeof cytoscape !== 'undefined' ){ // expose to global cytoscape (i.e. window.cytoscape)
      register( cytoscape );
    }

    if( typeof define !== 'undefined' && define.amd ){
      define( [], register );
    }

    module.exports = register;

**Comment by maxkfranz** [comment]
You have to setup your config yourself if you use amd

**Comment by shan-chalmers** [comment]
I'm getting the exact same error using webpack and es6 imports. Can you please elaborate a bit more on how to solve this?

**Comment by maxkfranz** [comment]
Webpack uses cjs `require()`, not amd

**Comment by shan-chalmers** [comment]
Thanks for your reply. More specifically I'm using [vue-loader](http://vue-loader.vuejs.org/en/)

I am importing the libraries like this:
```
import cytoscape from 'cytoscape';
import regCose from 'cytoscape-cose-bilkent';
```

**Comment by shan-chalmers** [comment]
I saw that you made a new release, which I just tried out and it solved the problem! Thank you so much.
