### ISSUE TITLE
"Uncaught ReferenceError: Point is not defined" using npm package

### ISSUE THREAD

**Issue by cmdcolin** [cytoscape/cytoscape.js-cose-bilkent#31]
Minimal test case, just run `yarn` and `gulp` to build https://github.com/cmdcolin/cytoscape-error-demo

I haven't looked into the cause yet but thought I'd follow up on #4

**Comment by maxkfranz** [comment]
@mj3cheun Would you please try this layout with your Webpack testing?  @cmdcolin's repo is another test case with Browserify.

**Comment by mj3cheun** [comment]
The issue is some of the src files are missing some of the requires it needs. This has been solved in commit 7230a9236db6658880be51f81b7d97582b98171e.

**Comment by cmdcolin** [comment]
looks fixed. thanks! I guess close for now :)
