### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js-cose-bilkent#32]
Please see 'https://github.com/iVis-at-Bilkent/chise.js/issues/106'

**Comment by metincansiper** [comment]
An important bug in layout after v1.3.8 is that 'during' layout is not working.

**Comment by maxkfranz** [comment]
@metincansiper The change you made will be problematic.  See my comment inline in your code for details

**Comment by metincansiper** [comment]
@maxkfranz Okey I got your point. I solved my previous problem with emitter (I think that it was caused by a simple mistake in code) and reverted the emitter to its original.

**Comment by metincansiper** [comment]
Solved the problem with during layout problem. But more work is needed here
to make the during layout as smooth as before.

**Comment by maxkfranz** [comment]
@metincansiper Great!  Thanks

**Comment by metincansiper** [comment]
It seems that the bug in 'https://github.com/iVis-at-Bilkent/chise.js/issues/106' is mainly caused by expand-collapse extension I solved it there.
