### ISSUE TITLE
cytoscape.js version spec in bower.json breaks downstream builds

### ISSUE THREAD

**Issue by nhambletCCRI** [cytoscape/cytoscape.js-cose-bilkent#33]
I'm using cytoscape.js-cose-bilkent project transitively. In the library I'm using, it has a dependency on version "^1.3.6", which is currently resolving to 1.5.2. Unfortuntely, this version has a depedency on cytoscape.js with version specification "^2.4.0 | ^3.0.0", which is not resolving for me (bower version 1.3.12 is giving me: bower ENORESTARGET  Tag/branch ^2.4.0 | ^3.0.0 does not exist). Is this a version specification error, or maybe my bower version is just too old, or maybe there's something else going on?

**Comment by maxkfranz** [comment]
@mj3cheun This needs `||`

**Comment by mj3cheun** [comment]
@maxkfranz Yup sorry, fixed pushed and ready for patch publish

**Comment by mj3cheun** [comment]
The fix is published on version 1.5.3. Try updating, thanks.

**Comment by nhambletCCRI** [comment]
Awesome! Thanks.
