### ISSUE TITLE
Investigate role of paddings in bad layouts

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js-cose-bilkent#35]
We need to investigate whether incompatibility between paddings in client and in l-level play a role in bad layouts. Also proper reflection of geometry from l-level to v-level might be the cause of such bad layouts. Notice also that vertical padding is more than horizontal one due to labels for compounds!

**Comment by d2fong** [comment]
@ugurdogrusoz did you ever find out if paddings affect the result of the layout?

**Comment by ugurdogrusoz** [comment]
@d2fong we fixed the incompatibility between paddings, which fixed some animation related issues but it's not apparently the reason we get bad layouts. Btw, I mean arbitrarily long inter-graph (inter-compartment) edges by bad layout. Since layout is an aesthetic issue, some people might find other layouts bad :)

**Comment by d2fong** [comment]
Okay good to know.  Thanks.
