### ISSUE TITLE
New layout option for incrementalness

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js-cose-bilkent#39]
We need a new layout option named initialEnergyOnIncremental. This will directly be used as the initial cooling factor. When user is asking for an incremental layout (randomize=false), how stable do they think the current layout is. A number in range (0.0, 1.0], default is whatever cooling factor we currently use by default on incremental layout (0.8?)

**Comment by hasanbalci** [comment]
Solved in 29424a1e721f8e76d7244477ac64c4828fe21c0b
