### ISSUE TITLE
CoSE-Bilkent "ReferenceError: LEdge is not defined"

### ISSUE THREAD

**Issue by monprin** [cytoscape/cytoscape.js-cose-bilkent#40]
I am using Cytoscape.js within React.js. I can use the bundled CoSE with no issues, and also I can use the Cola layout without issues, but when dropping CoSE-Bilkent in, I get the error that is shown in the screen cap.

![cose-bilkent_error](https://user-images.githubusercontent.com/7094030/27148232-27d46230-5105-11e7-9833-7a552783caab.png)

If you have any ideas what this might be or how to work around it, I would be quite grateful.

**Comment by monprin** [comment]
Also I forgot to mention, I am using Cytoscape.js version 3.1.1, cose-bilkent version 1.6.9, and react version 15.5.4. If there is any other information I can provide, please let m know.

**Comment by metincansiper** [comment]
@monprin this problem is supposed to be solved by 0d37f1b. Would you verify?

**Comment by monprin** [comment]
Well, good news and bad news. That did solve that error, but exposed a weirder error. Bilkent now registers just fine, but when the component is mounted, after the registration, when I call the general cytoscape initialization function, it just spins. It never goes anywhere, but there are no errors. It just get's stuck. I tried going back to past versions to see if they worked, but once I hit the 1.5.X series, I was getting a different error, so I am at a bit of a loss as to what is going on, any ideas?

**Comment by monprin** [comment]
By the way, I am roughly using [this](https://github.com/cytoscape/cytoscape.js/issues/1468#issuecomment-237669843) model for my react component.

**Comment by metincansiper** [comment]
@monprin what do you mean by initialization function it just spins and never goes to anywhere? How can I reproduce it?

**Comment by monprin** [comment]
Apologies on the delay, I did a little more experimentation and realized it was hanging because it was simply taking that long to run the layout. What parameters would recommend twekaing to improve performance (I'm looking at around 6000 edges and 400 nodes)? Otherwise I will just stick with traditional CoSE. Thanks for your help!

**Comment by ugurdogrusoz** [comment]
@monprin I suspect that no matter what layout algorithm you use, you won't get very meaningful results with such "dense" graphs (edge/node ratio is 60/4=15). So, if you have to visualize such dense (and large) graphs and you don't have compound/nested nodes in your graphs, I suggest you use some other, faster layout. CoSE is inherently slow (especially now, though we have plans to improve its run time performance from n^3 to n^2 in the future).
Regarding managing complexity, I strongly suggest you use some complexity management method to reduce size of your graphs (e.g. filter by some criteria, initially display a smaller graph of interest, group/cluster nodes into compounds and collapse them - see [this](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse) extension, etc.)
