### ISSUE TITLE
Improvement to force scheme

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js-cose-bilkent#41]
As discussed earlier, we should take compound weights (# of children) into account when cumulative forces are applied. In other words, we should divide the total force to compound weights to figure out movement amount. Recent repulsion force calculation was in a sense achieving this but not as clean as what's suggested here.

**Comment by ugurdogrusoz** [comment]
Once this is done, we should update the Java code base in chilay accordingly.

**Comment by hasanbalci** [comment]
Compound weights (# of children) are now taken into account in force calculations. Both JS and Java codes are updated accordingly. Current version produces better quality results and handles the long edge bug to a great extend.
