### ISSUE TITLE
"Wrong" behaviour when using padding, cytoscape-expand-collapse, and compoundPadding

### ISSUE THREAD

**Issue by d2fong** [cytoscape/cytoscape.js-cose-bilkent#42]
## Context
This is in reference to an issue @ugurdogrusoz had about the "pathways-search" app.
If I understand his concerns correctly, the "bad results" are related to node overlap.

Here is the original issue that Ugur posted on the pathway-commons dev group:
```
- why does cose-bilkent layout yield such bad layouts
(trust me I know the weaknesses of our algorithms but it doesn’t produce such layouts). 
please point us to the related repository if you’d like us to take a look. 
maybe something incorrect is getting done during collapse of complexes prior to display.

- consider using cytoscape.js-expand-collapse extension for expand-collapse of complexes (and compartments in my opinion)
```

Here is an example of a "bad layout" that I think Ugur is talking about, the cut-corner rectangle nodes are the ones that I frequently see overlapping, and those are the collapsed nodes:

![graph68968594](https://user-images.githubusercontent.com/2328291/27545745-a0a0bcec-5a5e-11e7-92ab-6c38331d2632.png)

I want to reiterate:
I am using  the ```cytoscape-expand-collapse``` extension.

I am using the following that I think are contributing factors to the problem:
* cytoscape-expand-collapse
* padding for nodes ( padding behaviour specified for cytoscape.js 3.x )

## Settings I use:
I use these settings:
```js
	cy.layout({
		name: 'cose-bilkent',
		paddingCompound: 50,
		fit: true,
		nodeRepulsion: 4500,
		idealEdgeLength: 50,
		edgeElasticity: 0.45,
		nestingFactor: 0.1,
		gravity: 0.25,
		numIter: 2500,
		tile: false,
		animationEasing: 'cubic-bezier(0.19, 1, 0.22, 1)',
		animate: 'end',
		animationDuration: 1000,
		randomize: true,
		tilingPaddingVertical: 20,
		tilingPaddingHorizontal: 20,
		gravityRangeCompound: 1.5,
		gravityCompound: 1.0,
		gravityRange: 3.8,
	}).run();
```

Which are mostly the same settings that you use for Newt, with the exception of ```tiling``` set to ```false```.  Either way, with tiling set to true/false it still produces the same result.

#### Increasing paddingCompound
- This doesn't seem to work on collapsed nodes. (I suspect that collapsed nodes are considered simple nodes when it's children are removed and therefore the option might not be applying)

Here is an example with paddingCompound set to different values:

paddingCompound: 50
![graph68968594](https://user-images.githubusercontent.com/2328291/27545979-52146708-5a5f-11e7-87dd-d72cccb9a5a5.png)

paddingCompound: 150
![graph86319220](https://user-images.githubusercontent.com/2328291/27546015-75eb0c7c-5a5f-11e7-92f9-b3b99d9bb605.png)

paddingCompound: 500
![graph721881](https://user-images.githubusercontent.com/2328291/27546093-c139baa2-5a5f-11e7-8d3f-b1859f39eb06.png)

As you can see, compoundPadding is not applying to the collapsed complex nodes, only the actual compartment compounds

**Comment by maxkfranz** [comment]
@d2fong Are you running the expand-collapse extension before or after the layout?  Maybe it conflicts if the layout hasn't finished yet.

**Comment by d2fong** [comment]
I am running the layout after I collapse all of the complex nodes.

**Comment by d2fong** [comment]
Posting some other findings I had in the google groups thread related to padding and node width / height.

### padding: 0;  complex node width/height: 45

Here is cose-bilkent run on a graph with:

collapsed complex nodes
dangling nodes filtered (compartment child nodes that do not have any edges between them)
![](https://lh3.googleusercontent.com/-bnTZziRZKTg/WU1tRDOiXXI/AAAAAAAAAAo/-W2LJI9iQ2UOZlWxrtNmP2eaaB0NV_Z4ACLcBGAs/s1600/Screen%2BShot%2B2017-06-23%2Bat%2B3.32.08%2BPM.png)

### padding: 22px;  complex node width/height: 45

Here is cose-bilkent run on signalling by bmp with:

collapsed complex nodes
dangling nodes filtered (compartment child nodes that do not have any edges between them)

I notice in this version that there is a little bit of node overlap when I introduce a non zero padding value.

![](https://lh3.googleusercontent.com/-G3QZVTEd0ag/WU1t-Ui13UI/AAAAAAAAAAw/VpGfrrac15gjg4v5Rf2htYz8IZ56wI_mwCLcBGAs/s1600/Screen%2BShot%2B2017-06-23%2Bat%2B3.27.53%2BPM.png)


### padding: 22px;  complex node width/height: 10

Here is cose-bilkent run on signalling by bmp with: (this is the configuration used for the search app)

collapsed complex nodes
dangling nodes filtered (compartment child nodes that do not have any edges between them)

![](https://lh3.googleusercontent.com/-gLbhdsF44pE/WU1ua9281jI/AAAAAAAAAA0/qANAXPjl2sIIbqykB-gqRRuRirNiopAVACLcBGAs/s1600/Screen%2BShot%2B2017-06-23%2Bat%2B3.25.59%2BPM.png)


In this one, there is a noticeable amount of overlap in the plasma_membrane compartment and some overlap in the early_endosome_membrane.  

Based on these images it would seem that padding on collapsed nodes seems to cause some issues, but I can't really know for sure I am not familiar with the cose-bilkent code base.  

The reason why I need to use the last configuration is because:
1. padding is required for my stylesheet to work
2. I don't want nodes collapsed nodes to be very big like the second picture

So that is why I need collapsed complex nodes to have a smaller height/width (10) while having a larger padding size (22px) so they fit in visually with the other nodes as well as enable me to put svg images onto them when they are expanded.

**Comment by d2fong** [comment]
I am experiencing similar behaviour in Newt when I change the width and height of complex nodes to 10, and then set the padding to be 22px.

Collapsed complex nodes seem to exhibit more node overlap using these settings.

![pc_signallingbybmp sbgn](https://user-images.githubusercontent.com/2328291/27554005-0ad60ab0-5a7b-11e7-90f4-df3e5044132c.png)

**Comment by d2fong** [comment]
Here is another example in Newt.

### collapsed complexes with no changes to padding and then running cose-bilkent:
![signalling2 sbgn](https://user-images.githubusercontent.com/2328291/27554724-5931c45e-5a7d-11e7-8a72-6e81e4ecb8d4.png)


### collapsed complexs, set padding to 22px, set height/width to 10, then running cose-bilkent:

![signalling2 sbgn 1](https://user-images.githubusercontent.com/2328291/27554747-6ce71f8a-5a7d-11e7-9068-b07ad5655316.png)

**Comment by d2fong** [comment]
## Steps to reproduce in Newt:

1.  Download this file, and load it into Newt:
[signalling2.sbgn.txt](https://github.com/cytoscape/cytoscape.js-cose-bilkent/files/1103199/signalling2.sbgn.txt)

2. collapse all complex nodes using the ui / expand collapse extension in the console

3. in the console, enter this line and run it:
```js
cy.nodes('[class="complex"]').style({'height': 10, 'width': 10, 'padding': 22})
```
4. run the cose-bilkent layout

**Comment by ugurdogrusoz** [comment]
@d2fong Here are some remarks:
- a collapsed complex should be a simple node, not a compound node; I don't understand why they get affected by "padding" changes
- any particular reason you're passing layout settings with default values (e.g. nodeRepulsion=4500)? sometimes we fine tune these defaults and you don't want to be using old defaults
- any particular reason you're setting tiling to false? if tiling is false, how come the complex members are getting tiled upon expand? Could it be that incremental layout invoked during expand is actually computing a layout for the inside of the complexes and you're overriding these locations by tiling members yourselves?
it's a holiday most of the week here but we'll investigate this issue asap.

**Comment by d2fong** [comment]
@ugurdogrusoz 
1.  Yes I know a collapsed node is a simple node.  I was trying compoundPadding because it came up in a search for "padding" in the issue.  You can take a look at all of the pictures that I posted and see for yourself that adding padding to a node produces node overlap.  Whether it is related to collapse-expand I don't know.

2. I just copied the settings that I found in Newt right here:  https://github.com/iVis-at-Bilkent/newt/blob/1b07c2659be51f6cb50453292faaab3a35fc5889/app/js/app-utilities.js#L10 
According to git they are 5 months old.  If they are stale I will ask you again, where can I find the most up to date recommended settings?

3.  I set tile to false a while ago because it was throwing an error that has probably since been fixed.  I just never changed it.  I will say again that setting it to true / false still produces this behaviour.

**Comment by d2fong** [comment]
Run cose-bilkent with the default settings as of 1.6.10.  Still node overlap

![graph55962119](https://user-images.githubusercontent.com/2328291/27556102-44b0a2fc-5a82-11e7-9834-ad466dc9dba6.png)

**Comment by ugurdogrusoz** [comment]
After some investigation, I suggest you try the following:
- call layout using:
        cy.layout({
		name: 'cose-bilkent',
		paddingCompound: 50,
		animationEasing: 'cubic-bezier(0.19, 1, 0.22, 1)',
		animationDuration: 1000,
		tilingPaddingVertical: 20,
		tilingPaddingHorizontal: 20,
	}).run();

   paddingCompound should be a value no more than the actual padding used for your compartments (if lower values result in no overlaps, feel free to use lower values to save space since this padding applies to complexes as well)

   we use default tiling here, which is true. this is crucial for expand-collapse to work properly

- set regular node paddings (simple node paddings) to 0 (zero). this is the most important reason you're getting overlaps since the nodes are drawn with the paddings but layout sees them without paddings

- make sure you pass cose-bilkent to expand-collapse extension to ensure incremental layout used during expand and collapse operations using cose-bilkent

- please let us know when the pathways search app is ready with these configurations so we can test.

**Comment by d2fong** [comment]
Okay.

I have some recommendations too.
1.  I recommend always putting the most up to date recommended settings in the readme.
2.  Until the padding issue is fixed I recommend documenting it as an incompatibility. 

I am unable to set padding to 0 for any simple node because padding is required for my stylesheet to work.  


What is incremental layout in expand-collapse supposed to do?

**Comment by ugurdogrusoz** [comment]
Thanks very much.

1. most up to date recommended settings are in the Readme as defaults. you shouldn't specify an option's value unless you're unhappy with that default. let me know if there is any setting you're unhappy with and perhaps I can recommend a value.

2. Just curious, what do you use paddings for? maybe we can take padding as an option and consider/respect it as well in cose-bilkent. currently they aren't.

when you expand or collapse a compound node, if layoutBy is not null (should be cose-bilkent in your case), an incremental layout (one that respects current node positions) is applied after the operation so that the map is tidied up during expand/collapse. for instance, during expand, if you don't apply an incremental layout expanding of a complex will often result in expanded larger complex overlapping with neighboring nodes.

**Comment by ugurdogrusoz** [comment]
Sorry padding wouldn't be an option since it can be set per node. It's already there but not currently considered. It should be considered.

**Comment by d2fong** [comment]
Okay I will defer to the setting values on the readme.

I use padding to place multiple svg images to make nodes look like this:
![screen shot 2017-06-27 at 11 14 23 am](https://user-images.githubusercontent.com/2328291/27595142-d87f68e0-5b29-11e7-86fe-1400204f33f8.png)

I believe discussions with Max a few months ago led me to use padding + svg image placement style properties to get this result.  So right now, the nodes in that image consist of a base node shape + multiple svg images set as a style property.  

It might be possible to alter this approach to use no padding.  But in my opinion it would be more productive and useful to make the layout compatible with paddings as it is a documented public style property in cytoscape.js.

Is there a particular reason / design decision as to why padding is not considered?  I can't make any promises that I will be able to fix it as I am unfamiliar with the cose-bilkent layout code but I could try to take a look and see if I can come up with something.

**Comment by ugurdogrusoz** [comment]
It should be rather straightforward for us to consider padding. I guess we never used nor noticed that paddings were there for simple nodes! It's a defficiency of our extension. We should be able to fix it soon.

**Comment by d2fong** [comment]
Okay, thanks for your support Ugur.  I'll try some of those things you suggested with the expand collapse extension.

**Comment by maxkfranz** [comment]
Some tips

- You can use `node.layoutDimensions()` to get the size of the node: http://js.cytoscape.org/#node.layoutDimensions
  - This already takes into account padding.
  - This gives you the option of including labels in the box in the layout options for free.  This is useful where you want big labels to give you more space.
- If you have a layout option that should have a value per element, then the option should be a function so custom values can be used, like `someVal: ele => node.data('someVal')`

**Comment by d2fong** [comment]
Ah it would be useful to add the includeLabelDimensions option to CoSE-Bilkent.  Let me try to use layoutDimensions instead

**Comment by maxkfranz** [comment]
It would be nice to have, but it depends on whether CoSE needs to use the padding values manually.  

If it does need the padding manually, then including the label in the w/h might give weird results. But if it's a small change, it's probably worth trying anyway.  It might work well enough.
