### ISSUE TITLE
`setTimeout()` used for synchronous layout case

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-cose-bilkent#45]
See https://github.com/cytoscape/cytoscape.js-cose-bilkent/blob/1.6.12/src/Layout/index.js#L261

There really shouldn't be a `setTimeout()` here.  It might seem to work ok for the `animate: 'end'` case, but it wouldn't work as expected for the `animate: false` case.

For `animate: false`, the layout is expected to run synchronously.

That is, `bar()` runs after the layout is done.

```js
cy.layout({ name: 'cose-bilkent', animate: false }).run();

bar();
```

This will always work:

```js
cy.one('layoutstop', bar);

cy.layout({ name: 'cose-bilkent', animate: false }).run();
```

However, there is an expectation --- and it's so stated in the docs --- that a discrete layout run should be synchronous.

**Comment by metincansiper** [comment]
@maxkfranz I removed that ```setTimeout()```. It seems to be not needed.

**Comment by maxkfranz** [comment]
That's great.  Thanks

**Comment by hasanbalci** [comment]
When we remove setTimeout for animate:end, animation does not work properly. Therefore, we now apply it when animate:end, and don't apply when animate:false. I think this is better.

**Comment by maxkfranz** [comment]
No other layout needs a timeout to make `layoutPositions()` work with animation.  This indicates that there is something wrong in the layout.  Maybe you're firing redundant events; `layoutPositions()` emits all the events if it's used.

**Comment by hasanbalci** [comment]
I reviewed this issue again, and yes, timeout is innocent. At that time, I thought that removing setTimeout caused the problem, but it is actually the very sharp values that we used for 'cubic-bezier' in animationEasing in Newt Editor. Therefore, I will remove the timeout again.
