### ISSUE TITLE
Calling .stop() on the layout doesn't stop the layout/animation

### ISSUE THREAD

**Issue by glampr** [cytoscape/cytoscape.js-cose-bilkent#58]
I'm trying to start and stop the layout programmatically.

While this works:
```js
var layout = cy.layout({ name: 'cose-bilkent' });
layout.run();
```
When after some time I try this:
```js
layout.stop();
```
nothing happens and the animation still runs.
The only difference I can see is that the layout object gets a new property ```stopped: true```.

**Comment by maxkfranz** [comment]
It should be checking whether it's stopped here: https://github.com/cytoscape/cytoscape.js-cose-bilkent/blob/master/src/Layout/index.js#L198

Obviously, you can only stop the layout if it's asynchronous.  If you ask it to run synchronously, you'd always be calling `stop()` after it's already done.

**Comment by glampr** [comment]
Hi @maxkfranz, it is not clear to me how to differentiate between starting the layout synchronously or asynchronously. By reading the documentation I understood that some layouts are synchronous, and some are asynchronous. Can you give me an example of how I should start the layout in a async way?

**Comment by maxkfranz** [comment]
`animate: during`

**Comment by glampr** [comment]
I'm already using that option and stopping still doesn't work for me. I will try to create a plunker to reproduce my issue.

**Comment by maxkfranz** [comment]
It's not going to work without #59

**Comment by ugurdogrusoz** [comment]
@glampr #59 is merged. Please try again, and close if working.

**Comment by glampr** [comment]
Works now, thanks!
