### ISSUE TITLE
Main file is built with code-coverage enabled

### ISSUE THREAD

**Issue by dcbrwn** [cytoscape/cytoscape.js-cose-bilkent#61]
https://github.com/cytoscape/cytoscape.js-cose-bilkent/blob/2a7014ffb2cb297403ba4332ed30422f29fbf5e5/cytoscape-cose-bilkent.js

**Comment by hasanbalci** [comment]
Code-coverage was because of the linkenlist library we used before. Now, we switched to another library and released a new version. It should be ok now.

**Comment by dcbrwn** [comment]
👍
