### ISSUE TITLE
No such layout `cose-bilkent` found

### ISSUE THREAD

**Issue by Habush** [cytoscape/cytoscape.js-cose-bilkent#62]
I am using Cytoscape on Angular 2 project and wanted to use **Cose-bilkent** layout. Hence I added the dependency to my project using _npm_. Since I am using Angular 2 with Typescript I have added the js module first to the **angular-cli.json** file then to the **index.html** file. After that in my _NetworkComponent_ , which is the angular component I am using to display the graph,  I am importing the library as follows:
`declare var CoSELayout:any;`

Then I am trying to use the layout as follows:
```
           this.cyto = cytoscape({
                    container: document.getElementById("graph"),
                    elements: this.graph.elements,
                    style: res.json()
                    });
            this.cyto.layout({name: "cose-bilkent"});
```
The graph displays but the layout is **not set to `cose-bilkent`** and I get the following error in the console:
`Can not apply layout: No such layout `cose-bilkent` found; did you include its JS file?`

How can I import cose-bilkent library and use it as my graph layout? What might be wrong here?

Thanks.

**Comment by Kkevsterrr** [comment]
Having this same issue and would love if anyone had any ideas!

**Comment by DumanBi** [comment]
Me too

**Comment by Habush** [comment]
I solved my issue by importing the layout library in my angular file:

```
var cytoscape = require('cytoscape/dist/cytoscape.js');

var coseLayout = require('cytoscape-cola/cytoscape-cose-bilkent.js');

cytoscape.use(coseLayout);
```
