### ISSUE TITLE
Critical : package.json:main is incorrect

### ISSUE THREAD

**Issue by d2fong** [cytoscape/cytoscape.js-cose-bilkent#63]
It points to the source code.  If you do this, you can't use Babel.

It should point to the built file.

**Comment by d2fong** [comment]
Max and Dylan made this change directly on master and unstable due to the critical nature of the bug.

**Comment by d2fong** [comment]
3.0.3 is released with this fix as the only change --- no code changes.

**Comment by ugurdogrusoz** [comment]
Thanks @d2fong @maxkfranz 
@hasanbalci please make 3.0.3 the latest release and make sure npm module is deployed as well
