### ISSUE TITLE
Function as nodeRepulsion option

### ISSUE THREAD

**Issue by mikpom** [cytoscape/cytoscape.js-cose-bilkent#71]
I was wondering if I could use arbitrary function as layout option `nodeRepulsion` argument?
Cose layout in the core allows that but I am getting an error if when using the same function for cose-bilkent.

Thanks,
Mikhail

**Comment by maxkfranz** [comment]
This is a good idea, but I would argue that it's generally more useful to set functions for the edge options, like the edge length.  Anyway, all element-related options should allow functions for per-element values -- like regular COSE -- not just node charge.

**Comment by DukeBaird** [comment]
A function for node repulsion or edge length would be quite helpful for me. I tried a quick modification but it seems to be more complicated that I had thought.

**Comment by bradh** [comment]
I just added a PR for edge length if you want to try it out - see #74

**Comment by ugurdogrusoz** [comment]
This is a duplicate of https://github.com/cytoscape/cytoscape.js-cose-bilkent/issues/1.
