### ISSUE TITLE
Cytoscape 3.3 objects in Vue.js state cause endless recursion

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js-cose-bilkent#84]
Is CoSE Bilkent compatible with Cytoscape 3.3?

CoSE Bilkent with Cytoscape 3.2.22 works fine. Cytoscape 3.3 however freezes the browser (100% CPU load). Same in Chrome and Safari. Happens only in (webpack) production mode.

I'm not sure if this is related to CoSE Bilkent at all but have you tested CoSE Bilkent with Cytoscape 3.3 already?

**Comment by maxkfranz** [comment]
Under what conditions is there an issue?

The demo seems to have the proper result (the layout is run on page load without animations): https://cytoscape.org/cytoscape.js-cose-bilkent/demo-compound.html

**Comment by jri** [comment]
Thank you for quick response!

I understand CoSE Bilkent is supposed to work with 3.3.

I've not yet investigated the problem in depth. CoSE Bilkent was just my first guess.

The freeze happens when a new node is about to appear. Just the border appear, then the browser freezes.

For `background-image` I use a function which renders the node as SVG and returns a `data:` URL.

Are there breaking changes in 3.3?

**Comment by maxkfranz** [comment]
Breaking changes would be made only in v4.

Could you make a demo that reproduces the issue?

**Comment by jri** [comment]
I'll try to make a demo in the next days. Thanks for the info!

**Comment by maxkfranz** [comment]
I tested the cytoscape@3.3.0 build on one of our apps that programmatically generates SVG images, and I've tested again just now.  It doesn't seem to have any issue there.  It's also using this layout.

I suspect the problem may be dependent on the SVG you are generating.

**Comment by jri** [comment]
Thanks for your testing!

I can confirm the problem is not related to Cytoscape SVG rendering.

Because it works in development mode, but not in production mode I guess the problem is rather in Webpack/Babel's code transformations than in Cytoscape itself.

Meanwhile I've tracked the problem down a little: when I drop my Cytoscape event handler code the problem goes away!

I need to programmatically select a Cytoscape element *without* emitting a `select` event. I realize this by unregistering the event handlers, then `ele.select()`, then registering the event handlers again.

```
class CytoscapeView {

  constructor {
    this.cy = cytoscape(...)
    this.onSelectNode   = this.nodeHandler('select')
    this.onSelectEdge   = this.edgeHandler('select')
    this.onUnselectNode = this.nodeHandler('unselect')
    this.onUnselectEdge = this.edgeHandler('unselect')
  }

  // programmatically selects an element without emitting a select event
  select (ele) {
    this.offSelectHandlers()
    ele.select()
    this.onSelectHandlers()
  }

  onSelectHandlers () {
    this.cy
      .on('select', 'node', this.onSelectNode)
      .on('select', 'edge', this.onSelectEdge)
  }

  offSelectHandlers () {
    this.cy
      .off('select', 'node', this.onSelectNode)
      .off('select', 'edge', this.onSelectEdge)
  }

  nodeHandler (...) {
    return e => {
      ...
    }
  }

  edgeHandler (...) {
    return e => {
      ...
    }
  }
}
```

Do you see any issue with this code from the Cytoscape perspective?

Have you any idea why Webpack/Babel apparently generates production code from that particular `class` construct that crashes the JS engine!?

My Webpack/Babel config is fairly minimal. Nothing too special.

I'm using the newest Webpack, Babel 6, and old Node 6.

Thank you for your effort!

**Comment by jri** [comment]
Sorry, I was wrong. The problem occurs in both, development mode *and* production mode! (I better had restart the dev server to realize this.) So, the problem is possibly related to Cytoscape 3.3.

I can narrow it down to a single line (see code above):
```
this.cy
      .on('select', 'node', this.onSelectNode)
      .on('select', 'edge', this.onSelectEdge)
```

With this line the browser freezes. Without it don't freeze.  
With Cytoscape 3.2.22 everything works fine.

I'll investigate it further and possibly come up with a demo.

**Comment by jri** [comment]
Meanwhile I have more insight. The problem occurs in Cytoscape 3.3 in conjunction with Vue.js. Apparently I have Cytoscape objects in my reactive Vue state.

Vue gains reactivity by converting object properties into getters/setters. This involves recursive traversal of the object structure. Apparently Cytoscape objects (Collection?) have a cyclic structure. This results in an endless loop in Vue.

Apparently the Cytoscape 3.3 data structures (Collection?) have internally changed since 3.2.22 in a way Vue can't handle anymore.

The solution would be for my app to *not* include Cytoscape objects in reactive app state. Frankly I was not aware I do that.

I use the latest Vue.js

**Comment by maxkfranz** [comment]
The element/collection data structure has been cyclic since 2.0.0.  You need that to handle elements like collections -- e.g. `ele[0]` is the same as `eles[0]`.

In any case, it's not really practical to allow anything to edit cytoscape's private data.  At the very least there would be performance concerns in replacing private json data with getters and setters.

The typical way to integrate with a component library is to read the values within a `render()` function or a template -- e.g. `ele.data('foo')`.  You can set listeners in the constructor of the component and set a dirty flag to indicate when the component needs to be re-rendered.  The react library is easy to set up this way.

An alternative, if the library absolutely requires intrusive wrapping, is to create wrapper objects that you fully control.  You may need a wrapper object for `cy` and one for each element.

E.g.:

```js
const wrapElementData = ele => {
  const data = {};
  const updateData = () => _.assign(data, _.clone(ele.data())); // write to data with a copy

  updateData(); // initial update
  ele.on('data', updateData); // update on change

  return data;
};
```

So then if you pass `wrapElementData(ele)` to a vue template, then it just gets a plain json object that it can safely wrap.

**Comment by jri** [comment]
OK, I will go with this approach then: holding plain data objects in app state (instead Cytoscape objects) and registering event listeners (e.g. `position`) to keep them in-sync. Thank you!

**Comment by jri** [comment]
Meanwhile I've refactored my application accordingly. Everything works fine now. Thank you for support!
