### ISSUE TITLE
Possible to create a planar graph?

### ISSUE THREAD

**Issue by jwmxyz** [cytoscape/cytoscape.js-cose-bilkent#85]
I am trying to achieve the below:

[![enter image description here][1]][1]

Instead it looks like this: 

[![enter image description here][2]][2]

I am using the [cose-bilkent][3] layout as per an example [here:][4] 

Is it possible to configure the settings to produce the desired outcome?

  [1]: https://i.stack.imgur.com/c9c15.png
  [2]: https://i.stack.imgur.com/p5cxz.png
  [3]: https://github.com/cytoscape/cytoscape.js-cose-bilkent
  [4]: https://github.com/cytoscape/cytoscape.js-cose-bilkent/issues/7

**Comment by ugurdogrusoz** [comment]
@jwmxyz this layout is a spring-embedder based one and it won't planarize or guarentee a plane drawing of planar graphs. if you try again (and again) you might get a plane embedding since it will start out from random positions.

**Comment by sancarn** [comment]
@ugurdogrusoz I've seen a few questions and answers with this. Do you know of any layout plugins which do force graphs to be "as planar as possible"?

**Comment by ugurdogrusoz** [comment]
@sancarn not that I know of as a Cytoscape.js extension. In literature some orthogonal layout algorithms use a planarization step but I am not aware of any specific implementations.

**Comment by sancarn** [comment]
I did find:
https://github.com/cytoscape/cytoscape.js-klay
Which seems to avoid a number of edge-edge intersections. But not all of them. However one can usually resolve them with few manual changes in between.

P.S. In some cases the graph might not be "planar embeddable", i.e. edge-edge intersections are inevitable.

**Comment by ugurdogrusoz** [comment]
@sarcarn Obviously not every graph is planar (otherwise we would call planar graphs just graphs :)
I assume you asked me whether or not there was a layout algorithm that guarantees a plane layout for a given planar graph. Neither klay nor cose guarantees that. [fcose](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose) does a better job in providing plane embeddings of planar graphs in general.
