### ISSUE TITLE
Is there a way to keep the nodes on a single Y axis?

### ISSUE THREAD

**Issue by NJBrearley** [cytoscape/cytoscape.js-cose-bilkent#86]
I am trying to utilise this layout and it works great, however it would be really useful to be able to specify if the non-compound nodes stay on a single axis and the movement happens on the other axis.

Is this possible?

**Comment by ugurdogrusoz** [comment]
@NJBrearley No, currently this layout style will not support such constraints. If you have large graphs you might want to consider [this extension](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose) instead. It's faster but minimal sacrifice from quality.
