### ISSUE TITLE
Multiple groups of nodes are distributed

### ISSUE THREAD

**Issue by MistyKuu** [cytoscape/cytoscape.js-cose-bilkent#87]
Hey,
 I have multiple groups of nodes which are not linked together. The algorithm distributes them on my whole viewport leaving a lot of empty space between each group. Is it possible to condense groups together so they use minimal amount of space required?

**Comment by ugurdogrusoz** [comment]
In fact, we are currently working on a utility for this in a separate repo, and hope to apply it to all algorithms produced by our lab. We'll let you know when it's ready!

**Comment by MistyKuu** [comment]
Sure thanks. I've just played with gravityRange and putting it to something smaller like 1.3 gives me pretty nice graph. Thanks!

**Comment by ugurdogrusoz** [comment]
Yes, increasing gravity should work to a certain extent. Tighter drawing can be obtained by some extra work as I said though. We'll keep you posted.
