### ISSUE TITLE
Uniform node dimensions

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js-cose-bilkent#91]
Back in the Java implementation of our algorithm, we had a flag to signify whether or not node dimensions are uniform. If the user set this flag, we would take *centers* of simple nodes into account and not perform the costly clipping point calculations. Could you please investigate if we lost this during the port to JavaScript?

**Comment by hasanbalci** [comment]
I exposed uniformNodeDimensions option d5008a0293b6018ca43a8c7bc89ace897b6d540e
