### ISSUE TITLE
Retain node positions when chart is being re-generated with the same dataset

### ISSUE THREAD

**Issue by zhpeh** [cytoscape/cytoscape.js-cose-bilkent#95]
**Issue type**

Feature request

**Desired behaviour**

I am trying to re-generate the same network chart by responding to button clicks to toggle the display of attributes (e.g. node names). All nodes and edges are exactly the same. However, each time the chart is being re-generated, the position of the nodes will shift. 

How can I retain the position of the nodes no matter how many times I regenerate the chart?

Appreciate any assistance here!

**Comment by ugurdogrusoz** [comment]
Same as https://github.com/cytoscape/cytoscape.js-cose-bilkent/issues/94, closing.

**Comment by zhpeh** [comment]
@ugurdogrusoz There isn't any solution/guide/hint/advice provided in #94, so how is this ticket closed?

**Comment by ugurdogrusoz** [comment]
This is a duplicate issue. Feel free to subscribe to and follow any development in the original issue please. Currently we do not have any resources to provide this new feature.
